version: '3.8'
services:
  zephyrus_web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Zephyrus
    depends_on: 
      - zephyrus_db
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
  zephyrus_db:
    container_name: DatabaseService
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: Zephyrus
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
  zephyrus_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - zephyrus_db
    restart: always
    environment:
      PMA_HOST: zephyrus_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
